// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "../node_modules/rescript/lib/es6/belt_Array.js";
import * as Caml_array from "../node_modules/rescript/lib/es6/caml_array.js";

var game = {
  status: /* InGame */0,
  current: /* O */1,
  board: Belt_Array.make(9, undefined)
};

var lines = [
  [
    0,
    1,
    2
  ],
  [
    3,
    4,
    5
  ],
  [
    6,
    7,
    8
  ],
  [
    0,
    3,
    6
  ],
  [
    1,
    4,
    7
  ],
  [
    2,
    5,
    8
  ],
  [
    0,
    4,
    8
  ],
  [
    2,
    4,
    6
  ]
];

function isFull(board) {
  return Belt_Array.every(board, (function (cell) {
                return cell !== undefined;
              }));
}

function marksInLine(board, mark, index) {
  return Belt_Array.some(Belt_Array.keep(lines, (function (inds) {
                    return Belt_Array.some(inds, (function (ind) {
                                  return ind === index;
                                }));
                  })), (function (inds) {
                return Belt_Array.every(inds, (function (ind) {
                              return Caml_array.get(board, ind) === mark;
                            }));
              }));
}

function computeStatus(board, mark, index) {
  if (marksInLine(board, mark, index)) {
    if (mark === /* O */1) {
      return /* O */2;
    } else {
      return /* X */1;
    }
  } else if (isFull(board)) {
    return /* Draw */3;
  } else {
    return /* InGame */0;
  }
}

function genCircle(param) {
  var circle = document.createElementNS("http://www.w3.org/2000/svg", "circle");
  circle.setAttribute("stroke", "black");
  circle.setAttribute("fill", "transparent");
  circle.setAttribute("stroke-width", (10.0).toString());
  circle.setAttribute("r", (10.0 * 3.5).toString());
  circle.setAttribute("cx", "50%");
  circle.setAttribute("cy", "50%");
  var title = document.createElement("title");
  title.text = "O";
  circle.appendChild(title);
  return circle;
}

function genCross(param) {
  var cross = document.createElementNS("http://www.w3.org/2000/svg", "path");
  cross.setAttribute("stroke", "black");
  cross.setAttribute("fill", "transparent");
  cross.setAttribute("stroke-width", (10.0).toString());
  cross.setAttribute("d", "M 15,15 L 85,85 M 85,15 L 15,85");
  var title = document.createElement("title");
  title.text = "X";
  cross.appendChild(title);
  return cross;
}

function drawMark(node, mark) {
  Belt_Array.forEach(node.childNodes, (function (e) {
          node.removeChild(e);
          
        }));
  var shape = mark ? genCircle(undefined) : genCross(undefined);
  node.appendChild(shape);
  
}

function showResult(result) {
  switch (result) {
    case /* InGame */0 :
        return ;
    case /* X */1 :
        alert("X wins!");
        return ;
    case /* O */2 :
        alert("O wins!");
        return ;
    case /* Draw */3 :
        alert("Draw game");
        return ;
    
  }
}

function tickFlow(e) {
  e.preventDefault();
  e.stopPropagation();
  var match = game.status;
  if (match !== 0) {
    return showResult(game.status);
  }
  var node = e.currentTarget;
  var index = Belt_Array.getIndexBy(Belt_Array.keep(document.querySelector("#board").children, (function (e) {
              return Belt_Array.getBy(e.classList, (function (c) {
                            return c === "cell";
                          })) !== undefined;
            })), (function (e) {
          return e === node;
        }));
  if (index === undefined) {
    return ;
  }
  Caml_array.set(game.board, index, game.current);
  var current = game.current;
  drawMark(node, current);
  var status = computeStatus(game.board, current, index);
  game.status = status;
  game.current = current;
  var match$1 = game.status;
  if (match$1 !== 0) {
    Belt_Array.forEach(document.querySelectorAll("#board > .cell"), (function (cell) {
            cell.addEventListener("click", tickFlow);
            
          }));
    return showResult(game.status);
  }
  var match$2 = game.current;
  if (match$2) {
    game.current = /* X */0;
  } else {
    game.current = /* O */1;
  }
  node.removeEventListener("click", tickFlow);
  
}

function resetBox(param) {
  return Belt_Array.forEach(document.querySelectorAll("#board > .cell"), (function (cell) {
                Belt_Array.forEach(cell.childNodes, (function (e) {
                        cell.removeChild(e);
                        
                      }));
                cell.addEventListener("click", tickFlow);
                
              }));
}

resetBox(undefined);

function reset(e) {
  e.preventDefault();
  e.stopPropagation();
  game.status = /* InGame */0;
  game.current = /* O */1;
  game.board = Belt_Array.make(9, undefined);
  return resetBox(undefined);
}

document.querySelector("main > button[type='reset']").addEventListener("click", reset);

var line_width = 10.0;

export {
  game ,
  lines ,
  isFull ,
  marksInLine ,
  computeStatus ,
  line_width ,
  genCircle ,
  genCross ,
  drawMark ,
  showResult ,
  tickFlow ,
  resetBox ,
  reset ,
  
}
/* game Not a pure module */
